"""initial_schema

Revision ID: fa91dea888e7
Revises: 
Create Date: 2026-04-30 22:43:48.332373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa91dea888e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_axes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lead_member_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_axes_id'), 'research_axes', ['id'], unique=False)
    op.create_index(op.f('ix_research_axes_title'), 'research_axes', ['title'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('communications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('communication_type', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('presentation_status', sa.Enum('SUBMITTED', 'ACCEPTED', 'PRESENTED', name='communicationpresentationstatus'), nullable=False),
    sa.Column('validation_status', sa.Enum('PENDING', 'VALIDATED', 'REJECTED', 'NEEDS_CORRECTION', name='validationstatus'), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('axis_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['axis_id'], ['research_axes.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communications_id'), 'communications', ['id'], unique=False)
    op.create_index(op.f('ix_communications_owner_id'), 'communications', ['owner_id'], unique=False)
    op.create_index(op.f('ix_communications_title'), 'communications', ['title'], unique=False)
    op.create_index(op.f('ix_communications_validation_status'), 'communications', ['validation_status'], unique=False)
    op.create_table('lab_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('program', sa.Text(), nullable=True),
    sa.Column('speakers', sa.Text(), nullable=True),
    sa.Column('visual_url', sa.String(length=500), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('UPCOMING', 'PAST', name='eventlifecyclestatus'), nullable=False),
    sa.Column('registration_link', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('validation_status', sa.Enum('PENDING', 'VALIDATED', 'REJECTED', 'NEEDS_CORRECTION', name='validationstatus'), nullable=False),
    sa.Column('axis_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['axis_id'], ['research_axes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_events_created_by'), 'lab_events', ['created_by'], unique=False)
    op.create_index(op.f('ix_lab_events_id'), 'lab_events', ['id'], unique=False)
    op.create_index(op.f('ix_lab_events_title'), 'lab_events', ['title'], unique=False)
    op.create_table('member_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('grade', sa.String(length=150), nullable=True),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('external_links', sa.Text(), nullable=True),
    sa.Column('orcid_id', sa.String(length=32), nullable=True),
    sa.Column('laboratory', sa.String(length=128), nullable=False),
    sa.Column('research_axis_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['research_axis_id'], ['research_axes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_profiles_id'), 'member_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_member_profiles_orcid_id'), 'member_profiles', ['orcid_id'], unique=False)
    op.create_index(op.f('ix_member_profiles_user_id'), 'member_profiles', ['user_id'], unique=True)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('validation_status', sa.Enum('PENDING', 'VALIDATED', 'REJECTED', 'NEEDS_CORRECTION', name='validationstatus'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_author_id'), 'news_items', ['author_id'], unique=False)
    op.create_index(op.f('ix_news_items_id'), 'news_items', ['id'], unique=False)
    op.create_index(op.f('ix_news_items_title'), 'news_items', ['title'], unique=False)
    op.create_index(op.f('ix_news_items_validation_status'), 'news_items', ['validation_status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('lead_member_name', sa.String(length=255), nullable=True),
    sa.Column('partners', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('funding', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('validation_status', sa.Enum('PENDING', 'VALIDATED', 'REJECTED', 'NEEDS_CORRECTION', name='validationstatus'), nullable=False),
    sa.Column('axis_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['axis_id'], ['research_axes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_table('validation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'VALIDATED', 'REJECTED', 'NEEDS_CORRECTION', name='validationstatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_records_content_id'), 'validation_records', ['content_id'], unique=False)
    op.create_index(op.f('ix_validation_records_content_type'), 'validation_records', ['content_type'], unique=False)
    op.create_index(op.f('ix_validation_records_id'), 'validation_records', ['id'], unique=False)
    op.create_index(op.f('ix_validation_records_submitted_by'), 'validation_records', ['submitted_by'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('publication_type', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('external_link', sa.String(length=500), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('validation_status', sa.Enum('PENDING', 'VALIDATED', 'REJECTED', 'NEEDS_CORRECTION', name='validationstatus'), nullable=False),
    sa.Column('axis_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['axis_id'], ['research_axes.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_doi'), 'publications', ['doi'], unique=False)
    op.create_index(op.f('ix_publications_id'), 'publications', ['id'], unique=False)
    op.create_index(op.f('ix_publications_owner_id'), 'publications', ['owner_id'], unique=False)
    op.create_index(op.f('ix_publications_title'), 'publications', ['title'], unique=False)
    op.create_index(op.f('ix_publications_validation_status'), 'publications', ['validation_status'], unique=False)
    op.create_index(op.f('ix_publications_year'), 'publications', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_year'), table_name='publications')
    op.drop_index(op.f('ix_publications_validation_status'), table_name='publications')
    op.drop_index(op.f('ix_publications_title'), table_name='publications')
    op.drop_index(op.f('ix_publications_owner_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_doi'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_validation_records_submitted_by'), table_name='validation_records')
    op.drop_index(op.f('ix_validation_records_id'), table_name='validation_records')
    op.drop_index(op.f('ix_validation_records_content_type'), table_name='validation_records')
    op.drop_index(op.f('ix_validation_records_content_id'), table_name='validation_records')
    op.drop_table('validation_records')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_by'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_news_items_validation_status'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_title'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_id'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_author_id'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_member_profiles_user_id'), table_name='member_profiles')
    op.drop_index(op.f('ix_member_profiles_orcid_id'), table_name='member_profiles')
    op.drop_index(op.f('ix_member_profiles_id'), table_name='member_profiles')
    op.drop_table('member_profiles')
    op.drop_index(op.f('ix_lab_events_title'), table_name='lab_events')
    op.drop_index(op.f('ix_lab_events_id'), table_name='lab_events')
    op.drop_index(op.f('ix_lab_events_created_by'), table_name='lab_events')
    op.drop_table('lab_events')
    op.drop_index(op.f('ix_communications_validation_status'), table_name='communications')
    op.drop_index(op.f('ix_communications_title'), table_name='communications')
    op.drop_index(op.f('ix_communications_owner_id'), table_name='communications')
    op.drop_index(op.f('ix_communications_id'), table_name='communications')
    op.drop_table('communications')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_research_axes_title'), table_name='research_axes')
    op.drop_index(op.f('ix_research_axes_id'), table_name='research_axes')
    op.drop_table('research_axes')
    # ### end Alembic commands ###
